import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Component from '@/components/ui/custom/navbar';
import Footer from '@/components/ui/custom/footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Gitf Hub',
  description: 'Generated by Muhammad Ali',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="impact-site-verification"
          value="381351a2-925a-4b6d-8b27-fdc966747e83"
        ></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Component />
        {children}
        <Footer />
      </body>
    </html>
  );
}
